// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
)

type Product struct {
	ProductID  int32
	Name       sql.NullString
	Price      sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}

type User struct {
	UserID     int32
	Name       sql.NullString
	Email      sql.NullString
	Password   sql.NullString
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
	IsAdmin    sql.NullBool
}

type UserProduct struct {
	UserProductID sql.NullInt32
}
